#! /usr/bin/env bash

# Watch paths and restart <command> on detected changes
# Usage: runner <command> <path1> ...

command="$1"
shift

if [ -z "$@" ]
then
    echo "No filename(s) provided for monitoring"
    exit 225
fi

trap "run=false" 1 2 3 15

run=true pid= previous_hash= && while $run
do
    new_hash=$(for path in $@; do find "${path}" -ls; done | md5sum)

    if [ "${previous_hash}" != "${new_hash}" ]
    then
        if [ -n "${pid}" ]
        then
            kill "${pid}"
            sleep 2
            pid=
        fi

        bash -c "${command}" & pid=$!
        echo "(re)started as pid ${pid} after hash change" >&2
    fi

    previous_hash="${new_hash}"
    sleep 15
done

echo "Exited after user interruption" >&2

if [ -n "${pid}" ]
then
    kill "${pid}"
fi
