#! /usr/bin/env bash

ACTION="$1"
VERSION="$2"

VARDIR="/var/lib/dpkg/info"
PACKAGE_NAME="${DPKG_MAINTSCRIPT_PACKAGE}"
LISTFILE="${VARDIR}/${PACKAGE_NAME}.list"
PACKAGE_DIR=$(grep "${PACKAGE_NAME}"'$' < "${LISTFILE}" | head -1)

create_path_files() {
    {
        echo '#!/usr/bin/env bash'
        echo 'export PATH="${PATH}:'"/opt/${PACKAGE_NAME}/bin"'"'
    } > /etc/profile.d/${PACKAGE_NAME}.sh

    chmod 755 /etc/profile.d/${PACKAGE_NAME}.sh
}

remove_path_files() {
    rm /etc/profile.d/${PACKAGE_NAME}.sh
}

case "$ACTION" in
    configure)
        create_path_files
        ;;

    remove|upgrade)
        remove_path_files
        ;;
esac
