#!/usr/bin/env bash

http::postit::response_post() {
    local _method="${1}"
    local _request="${2}"
    local _headers="${3}"
    local _content="${4}"
    local _b64_content="${5}"

    echo "${_b64_content}" | base64 --decode | http::response_octet_stream
}

http::postit::url_mappings() {
    url::add_handler '^\/post$' POST http::postit::response_post
}
