#! /usr/bin/env bash

http::primary::response_index() {
    http::response_file GET index.html "${3}" # Pass back the original headers
}

http::primary::url_mappings() {
    url::add_handler '^\/$' GET http::primary::response_index
    url::add_handler '^\/index.html$' GET http::primary::response_index
}
